trigger:
  - none

pool:
  name: Default

stages:
- stage: Plan
  displayName: 'Terraform Plan'
  jobs:
  - job: TerraformPlan
    displayName: 'Terraform Plan'
    steps:
    - task: JasonBJohnson.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-installer.TerraformInstaller@1
      inputs:
        terraformVersion: '0.12.31'

    - script: |
        terraform --version
        terraform init
      displayName: 'Terraform Init and Plan'
