trigger:
  - none

pool:
  name: Default

steps:
# Terraform Install
- task: JasonBJohnson.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-installer.TerraformInstaller@1
  displayName: install terraform
  inputs:
      terraformVersion: 0.12.31
        
- task: AzureCLI@2
  displayName: "DEVRFT:TF Initalize"
  continueOnError: false
  inputs:
      azureSubscription: 'MCAPS-Support-REQ-79844-2024-ajoubert(e30ed3f0-4b47-4f89-bad0-4648a0ef5616)'
      scriptType: "bash"
      scriptLocation: "inlineScript"
      inlineScript: |
        az login
        terraform init
