trigger:
  - none

pool:
  name: Default

steps:
# Terraform Install
- task: JasonBJohnson.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-installer.TerraformInstaller@0
  displayName: install terraform
  inputs:
      terraformVersion: 0.15.5
        
- task: AzureCLI@2
  displayName: "DEVRFT:TF Initalize"
  continueOnError: false
  inputs:
      azureSubscription: 'aca-tf-sc-2'
      scriptType: "bash"
      scriptLocation: "inlineScript"
      inlineScript: |
        export TF_LOG="TRACE"
        export ARM_SUBSCRIPTION_ID=$(subscriptionid)
        export ARM_CLIENT_ID=$(clientid)
        export ARM_CLIENT_SECRET=$(clientsecret)
        export ARM_TENANT_ID=$(tenantid)
        terraform init -input=false
        terraform plan -out=tfplan
      addSpnToEnvironment: true
