trigger:
  - none

pool:
  name: Default

steps:
# Terraform Install
- task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
  displayName: install terraform
  inputs:
      terraformVersion: 0.12.31
        
- task: AzureCLI@2
  displayName: "DEVRFT:TF Initalize"
  continueOnError: false
  inputs:
      azureSubscription: 'MCAPS-Support-REQ-79844-2024-ajoubert(e30ed3f0-4b47-4f89-bad0-4648a0ef5616)'
      scriptType: "bash"
      scriptLocation: "inlineScript"
      inlineScript: |
        export TF_LOG="TRACE"
        export ARM_SUBSCRIPTION_ID=$(subscriptionid)
        export ARM_CLIENT_ID=$(clientid)
        export ARM_CLIENT_SECRET=$(clientsecret)
        export ARM_TENANT_ID=$(tenantid)
        terraform init 
