trigger:
  - none

pool:
  name: Default

stages:
- stage: Plan
  displayName: 'Terraform Plan'
  jobs:
  - job: TerraformPlan
    displayName: 'Terraform Plan'
    steps:
    - task: JasonBJohnson.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-installer.TerraformInstaller@1
      inputs:
        terraformVersion: '0.12.31'

    - script: |
        terraform --version
        terraform init  -backend-config="storage_account_name=acatfstorage" -backend-config="container_name=tfconfig" -backend-config="key=terraform.tfconfig" -backend-config="access_key=$(accessKey)"
      displayName: 'Terraform Init and Plan'
